// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgatoynjisxtnvcbugef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYXRveW5qaXN4dG52Y2J1Z2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDI3NDUsImV4cCI6MjA3MDMxODc0NX0.2Ebc3_UcZjiAMzqYDAB1s7Xxh-wBv72adSvV0cqirOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});